accelerate launch train.py \
    --model_name_or_path "/mnt/home/mstahl/argpaca/models/gemma-2-9b" \
    --data_path /mnt/home/mstahl/argpaca/code/stanford_alpaca/alpaca_data.json \
    --bf16 True \
    --output_dir /mnt/home/mstahl/argpaca/models/gemma-2-9b-instruct \
    --num_train_epochs 3 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 5e-6 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'Gemma2DecoderLayer' \
    --tf32 True
